// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coanrswmadkrqgagblxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvYW5yc3dtYWRrcnFnYWdibHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzU5NjcsImV4cCI6MjA1NzkxMTk2N30.D_0GTZHMCbQ7EJjmDZSbZYMRX42xL42osd2utgePBDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);